INSERT INTO {OMOP_SCHEMA}.drug_exposure
(
    drug_exposure_id,
    person_id
    drug_concept_id,
    drug_exposure_start_date,
    drug_exposure_start_datetime,
    drug_exposure_end_date,
    drug_exposure_end_datetime,
    drug_type_concept_id,
    quantity,
    days_supply,
    --provider_id,
    --visit_occurrence_id,
    --visit_detail_id,
    drug_source_value,
    drug_source_concept_id,
    dose_unit_source_value,
)
SELECT
    drug_exposure_id,
    person_id
    drug_concept_id,
    drug_exposure_start_date,
    drug_exposure_start_datetime,
    drug_exposure_end_date,
    drug_exposure_end_datetime,
    drug_type_concept_id,
    quantity,
    days_supply,
    --provider_id,
    --visit_occurrence_id,
    --visit_detail_id,
    drug_source_value,
    drug_source_concept_id,
    dose_unit_source_value,
FROM {OMOP_SCHEMA}.stg__drug_exposure;